# Generated by Django 5.0.3 on 2024-04-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areaprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('is_professor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('resumo', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.areaprojeto')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.campus')),
                ('pessoas', models.ManyToManyField(to='pesquisa.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('detalhe', models.TextField()),
                ('date_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateField()),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.pessoa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.projeto')),
            ],
        ),
    ]
